apiVersion: v1
kind: Pod
metadata:
  name: fortune-https
  labels:
    app.kubernetes.io/name: fortune
    app.kubernetes.io/part-of: distributed-playground
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    # -------------------------------------------------------
    # METHOD D: Mounting ConfigMap as a Volume
    # -------------------------------------------------------
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
      # NOTE: This MOUNT hides any existing files in /etc/nginx/conf.d
      # If you need to add a single file without hiding others,
      # use 'subPath' (but be aware this breaks auto-updates).

    # -------------------------------------------------------
    # METHOD E: Mounting Secrets as a Volume
    # -------------------------------------------------------
    - name: certs
      mountPath: /etc/nginx/certs/
      readOnly: true
      # Secrets are mounted into an in-memory filesystem (tmpfs).
      # They are never written to physical disk.

  volumes:
  - name: config
    configMap:
      name: fortune-config
      # -----------------------------------------------------
      # PERMISSIONS (Octal)
      # 0644 = User: Read/Write, Group: Read, World: Read
      # Standard for config files.
      # -----------------------------------------------------
      defaultMode: 0644
      # Optional: Select specific items to expose
      items:
      - key: my-nginx-config.conf
        path: https.conf # Renames the file inside the container

  - name: certs
    secret:
      secretName: fortune-https
      # -----------------------------------------------------
      # PERMISSIONS (Octal)
      # 0400 = User: Read-only. Everyone else: No access.
      # BEST PRACTICE for private keys and certs.
      # -----------------------------------------------------
      defaultMode: 0400
